package org.dclar.mybatis.model;

import java.util.Date;

public class ActEvtLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.LOG_NR_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private Long logNr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.TYPE_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.PROC_DEF_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.EXECUTION_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.TASK_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.TIME_STAMP_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private Date timeStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.USER_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.LOCK_OWNER_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private String lockOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.LOCK_TIME_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private Date lockTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.IS_PROCESSED_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private Byte isProcessed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_EVT_LOG.DATA_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.LOG_NR_
     *
     * @return the value of ACT_EVT_LOG.LOG_NR_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public Long getLogNr() {
        return logNr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.LOG_NR_
     *
     * @param logNr the value for ACT_EVT_LOG.LOG_NR_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setLogNr(Long logNr) {
        this.logNr = logNr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.TYPE_
     *
     * @return the value of ACT_EVT_LOG.TYPE_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.TYPE_
     *
     * @param type the value for ACT_EVT_LOG.TYPE_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.PROC_DEF_ID_
     *
     * @return the value of ACT_EVT_LOG.PROC_DEF_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.PROC_DEF_ID_
     *
     * @param procDefId the value for ACT_EVT_LOG.PROC_DEF_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.PROC_INST_ID_
     *
     * @return the value of ACT_EVT_LOG.PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.PROC_INST_ID_
     *
     * @param procInstId the value for ACT_EVT_LOG.PROC_INST_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.EXECUTION_ID_
     *
     * @return the value of ACT_EVT_LOG.EXECUTION_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.EXECUTION_ID_
     *
     * @param executionId the value for ACT_EVT_LOG.EXECUTION_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.TASK_ID_
     *
     * @return the value of ACT_EVT_LOG.TASK_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.TASK_ID_
     *
     * @param taskId the value for ACT_EVT_LOG.TASK_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.TIME_STAMP_
     *
     * @return the value of ACT_EVT_LOG.TIME_STAMP_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.TIME_STAMP_
     *
     * @param timeStamp the value for ACT_EVT_LOG.TIME_STAMP_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.USER_ID_
     *
     * @return the value of ACT_EVT_LOG.USER_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.USER_ID_
     *
     * @param userId the value for ACT_EVT_LOG.USER_ID_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.LOCK_OWNER_
     *
     * @return the value of ACT_EVT_LOG.LOCK_OWNER_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public String getLockOwner() {
        return lockOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.LOCK_OWNER_
     *
     * @param lockOwner the value for ACT_EVT_LOG.LOCK_OWNER_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setLockOwner(String lockOwner) {
        this.lockOwner = lockOwner == null ? null : lockOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.LOCK_TIME_
     *
     * @return the value of ACT_EVT_LOG.LOCK_TIME_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.LOCK_TIME_
     *
     * @param lockTime the value for ACT_EVT_LOG.LOCK_TIME_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.IS_PROCESSED_
     *
     * @return the value of ACT_EVT_LOG.IS_PROCESSED_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public Byte getIsProcessed() {
        return isProcessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.IS_PROCESSED_
     *
     * @param isProcessed the value for ACT_EVT_LOG.IS_PROCESSED_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setIsProcessed(Byte isProcessed) {
        this.isProcessed = isProcessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_EVT_LOG.DATA_
     *
     * @return the value of ACT_EVT_LOG.DATA_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_EVT_LOG.DATA_
     *
     * @param data the value for ACT_EVT_LOG.DATA_
     *
     * @mbg.generated Wed Jan 17 18:14:29 CST 2018
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}